### PR TITLE
Unignore StreamFilesPTest

### PR DESCRIPTION
**Pull request by cangencer**

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
The previous "test failed" was due to "VM crash or calling System.exit()". The StreamFilesPTest, according to logs, was run without failures.

**Comment by cangencer** [comment]
verify

**Comment by viliam-durina** [comment]
another crash: https://hazelcast-l337.ci.cloudbees.com/job/Jet-pr-builder/1357/

**Comment by cangencer** [comment]
verify

**Comment by viliam-durina** [comment]
now, `WriteFilePTest` failed, but not `StreamFilesPTest: https://hazelcast-l337.ci.cloudbees.com/job/Jet-pr-builder/1366/

**Comment by mtopolnik** [comment]
Closing as superseded by #395.

**Pull request closed without merging**
