### PR TITLE
Introduce JetSqlService

### PR DESCRIPTION
**Pull request by gierlachg**
Introduced `JetSqlService` as an entry point for SQL statements execution in Jet.

Created `hazelcast-jet-sql` module and the initial implementation of `JetSqlCoreBackend` that is required by IMDG SQL engine to support Jet specific SQL statements. `hazelcast-jet-sql` module is built as a single, fat & shaded jar containing all dependencies.

As of now only IMDG compatible queries can be executed as no Jet extensions are implemented yet.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3167/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3167/jet-oss-pr-builder-3167.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java:431: Line is longer than 123 characters (found 125). [LineLength]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3168/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3168/jet-oss-pr-builder-3168.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project hazelcast-jet-sql: MavenReportException: Error while generating Javadoc: 
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobMetrics_NonSharedClusterTest.when_noMetricCollectionYet_then_emptyMetrics:81
[INFO] 
[ERROR] Tests run: 2208, Failures: 1, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3169/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3169/jet-oss-pr-builder-3169.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project hazelcast-jet-sql: MavenReportException: Error while generating Javadoc: 
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3172/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3172/jet-oss-pr-builder-3172.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project hazelcast-jet-sql: MavenReportException: Error while generating Javadoc: 
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3173/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3173/jet-oss-pr-builder-3173.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts:101 ? WrongTarget
[INFO] 
[ERROR] Tests run: 2208, Failures: 0, Errors: 1, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by gierlachg** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3174/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3174/jet-oss-pr-builder-3174.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaP_StandaloneKafkaTest.when_cancelledAfterBrokerDown_then_cancelsPromptly:62 durationSeconds=58
[INFO] 
[ERROR] Tests run: 31, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by gierlachg** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3175/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3175/jet-oss-pr-builder-3175.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-assembly-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-assembly-plugin:jar:3.0.0: Could not transfer artifact org.apache.maven.plugins:maven-assembly-plugin:pom:3.0.0 from/to nexus-proxy (http://jenkins.hazelcast.com:8081/content/repositories/central/): Transfer failed for http://jenkins.hazelcast.com:8081/content/repositories/central/org/apache/maven/plugins/maven-assembly-plugin/3.0.0/maven-assembly-plugin-3.0.0.pom: Unknown host jenkins.hazelcast.com: No address associated with hostname -> [Help 1]
--------------------------
</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3180/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3180/jet-oss-pr-builder-3180.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Job_SeparateClusterTest.stressTest_getJobStatus_client:164->stressTest_getJobStatus:211 ? Execution
[INFO] 
[ERROR] Tests run: 2208, Failures: 0, Errors: 1, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Review by viliam-durina — APPROVED** [review]

**Comment by viliam-durina** [comment]
verify

**Pull request closed without merging**
