### PR TITLE
Fixed creation of RecordWriter for HdfsWriteP

### PR DESCRIPTION
**Pull request by flostadler**
Changed the creation of the RecordWriter to receive its own copy
	of the JobConf. That way changes to the JobConf will not infer
	with other RecordWriters.

### CODE REVIEW

**Comment by flostadler** [comment]
#1309

**Comment by gurbuzali** [comment]
Hi Florian, the PR looks good. Can you please sign the Contributor License Agreement?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

**Comment by flostadler** [comment]
Sure, i'm doing it right now

**Comment by gurbuzali** [comment]
verify

**Comment by gurbuzali** [comment]
Thank you @flostadler for the PR

**Pull request merged**
