### PR TITLE
[Don't merge]  PR to test new arguments at Jenkins

### PR DESCRIPTION
**Pull request by hasancelik**

### CODE REVIEW

**Comment by hasancelik** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by mtopolnik** [comment]
verify

**Comment by mtopolnik** [comment]
verify

**Comment by viliam-durina** [comment]
The test succeeded with 1g heap

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
Second pass with 1g heap.

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Pull request closed without merging**
