### PR TITLE
Add SPI to customize the job classloader.

### PR DESCRIPTION
**Pull request by renatobertacco**

### CODE REVIEW

**Comment by renatobertacco** [comment]
Add a strategy for contributing a job class-loader factory

**Comment by cangencer** [comment]
@renatobertacco Thanks for the PR, please have a glance at the https://github.com/hazelcast/hazelcast-jet#contributing-to-hazelcast-jet section.

Regarding your PR, could you also write a short summary for the motivation and also possibly atest ?

**Comment by renatobertacco** [comment]
@cangencer I added the unit test and a short summary for the motivation as you required. Let me know if you need something else.

**Comment by cangencer** [comment]
I mean can you describe your use case and why you need this. Not as part of the code. I would prefer to understand your needs and discuss how it should be best implemented first. From what I can see you need to use a custom class loader when running the job. How do you intend to use this?

**Comment by renatobertacco** [comment]
I would like to use Hazelcast Jet inside an OSGi run-time. JetService gets a single class loader for every job. Reading your documentation you say
to set the class in the JobConfig for deserialising the lamba expression in the correct way but this cannot work if every job needs a different class-loader as happens in OSGi run-time where the class-loader are isolated. 
Here a job can be created from different OSGi bundles. Since every OSGi bundle has its own class-loader it is necessary to have 
a strategy which allows finding the correct bundle class-loader for the given job in order to allow deserialising the lambda expressions, processors and so on.

Using this SPI feature, I can setting a class-loader in Hazelcast Config and so I can load the SPI JobClassLoaderFactory which can get the correct classloader using the jobId.
In my implementation immediately after creating the job I put in a distributed map the bundle name using the jobId as key. The JobClassLoaderFactory can find the job OSGi bundle
using the distributed map and returns the correct class-loader.

**Comment by viliam-durina** [comment]
Can you post your implementation of `JobClassLoaderFactory ` so that we can see what are you doing in it?

**Comment by viliam-durina** [comment]
Also, how do you make that the jet bundle is able to see the `JobClassLoaderFactory`? Do you add it to the bundle? Normally, one bundle cannot see another bundle unless it imports it, afaik.

**Comment by renatobertacco** [comment]
My draft JobClassLoaderFactory implementation is this

```
public class JobClassLoaderFactoryImpl implements JobClassLoaderFactory {

    Map<String, ClassLoader> symbolicName2ClassLoader = new HashMap<String, ClassLoader>();

    @Override
    public ClassLoader getJobClassLoader(long jobId, HazelcastInstance hi, Map<String, byte[]> resources) {
        IMap<Long, String> jobId2BundleName = hi.getMap(RESOURCES_MAP_NAME_PREFIX);
        String symbolicName = jobId2BundleName.get(jobId);
        return getClassLoader(symbolicName);
    }
    
    private ClassLoader getClassLoader(String symbolicName) {
        return symbolicName2ClassLoader.computeIfAbsent(symbolicName, (symbolicBundleName) -> {
            Bundle bundle = getBundle(symbolicBundleName);
            if (bundle!=null) {
                return bundle.adapt(BundleWiring.class).getClassLoader();
            } else {
                return null;
            }
        });
    }
    
    private Bundle getBundle(String symbolicName) {
        Bundle[] allBundles = FrameworkUtil.getBundle(getClass()).getBundleContext().getBundles();
        for (Bundle bundle : allBundles) {
            if (bundle.getSymbolicName().equals(symbolicName)) {
                return bundle;
            }
        }
        return null;
    }
}
```
For loading it I set the bundle classloader in the hazelcast instance Config

**Comment by cangencer** [comment]
@renatobertacco is your class loader factory deployed alongside the hazelcast-jet bundle, so it has always access to it?

**Comment by renatobertacco** [comment]
I set in the hazelcast instance config my classloader. Something similar to:
```
hiConfig.setClassLoader(new MyBundleClassLoader(hiConfig.getClassLoader()));
```
In this way the ServiceLoader is able to load my JobClassLoaderFactoryImpl

**Comment by viliam-durina** [comment]
@renatobertacco can you have a look at this [commit](https://github.com/viliam-durina/hazelcast-jet/commit/25ee67f01e76860344c11f48d4ec8604ece9e647)? It should serve the same purpose as yours, but is simpler. You don't need an `IMap` to map from jobId to symbolic name, you can pass the symbolic name directly.

You will have 3 bundles on members:
1. bundle with your custom CL implementation
```
public class OsgiJobClassLoaderFactory implements JobClassLoaderFactory {
    private final String symbolicName;
    public OsgiJobClassLoaderFactory(String symbolicName) {
        this.symbolicName = symbolicName;
    }
    public ClassLoader getJobClassLoader() {
        // ... code to get the class loader using the symbolic name
    }
}
```
2. bundle with hazelcast jet, that will be configured to use bundle <span>#</span>1 in `Config.setClassLoader`
3. bundle with your job

On client, you'll submit the job like this:
```
JobConfig config = new JobConfig()
        .setClassLoaderFactory(new OsgiJobClassLoaderFactory("foo.symbolic.name"));
```

Can you confirm that this works for you?

**Comment by viliam-durina** [comment]
There is also a race in your PR: you first have to submit the job and then you add mapping to `IMap`. It could happen that the job will try to query the map before you manage to insert the mapping.

Also when you use a cache in the `OsgiJobClassLoaderFactory`, implement is using a `ConcurrentMap`, as it will be accessed from different threads without synchronization.

**Comment by renatobertacco** [comment]
@viliam-durina I agree with you, to set the JobClassLoaderFactory into JobConfig is a good approach and as general idea it works, but currently there is an issue. The JobConfig can be accessed from JobCoordinationService  only by master member:

```
public class JobCoordinationService {
    ...
    public JobConfig getJobConfig(long jobId) {
        if (!isMaster()) {
            throw new JetException("Cannot query config of Job " + idToString(jobId) + ". Master address: "
                    + nodeEngine.getClusterService().getMasterAddress());
        }
       ...
```
I do not know why there is this check but your code cannot work with it.

**Comment by viliam-durina** [comment]
@renatobertacco Are you really getting `JetException: Cannot query config of Job ...` exception? Can you send the stack trace?

**Comment by renatobertacco** [comment]
@viliam-durina  the stacktrace is

```
2018-03-09 17:39:50,554  WARN | hz._HZ_INSTANCE___GROUP_testjet5701.async.thread-8 | com.hazelcast.jet.impl.MasterContext                    | [10.0.5.11]:5701 [GROUP_testjet] [0.6-SNAPSHOT] Execution of job 3d9b-6af9-c9bd-e5bb, execution 5d8b-8f5a-413b-678b failed in 4291 ms 
com.hazelcast.jet.JetException: Cannot query config of Job 3d9b-6af9-c9bd-e5bb. Master address: [10.0.5.11]:5701
	at com.hazelcast.jet.impl.JobCoordinationService.getJobConfig(JobCoordinationService.java:392)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$getClassLoader$0(JobCoordinationService.java:105)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$getClassLoader$0(JobExecutionService.java:77)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.hazelcast.jet.impl.JobExecutionService.getClassLoader(JobExecutionService.java:77)
	at com.hazelcast.jet.impl.JobCoordinationService.getClassLoader(JobCoordinationService.java:111)
	at com.hazelcast.jet.impl.JetService.getClassLoader(JetService.java:154)
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.deserializePlan(InitExecutionOperation.java:113)
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:66)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19(MasterContext.java:620)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:615)
	at com.hazelcast.jet.impl.MasterContext.tryStartJob(MasterContext.java:216)
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:273)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1(JobCoordinationService.java:197)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by viliam-durina** [comment]
@renatobertacco can you review #770 now if it works for you?

**Comment by renatobertacco** [comment]
@viliam-durina now it works

**Comment by cangencer** [comment]
@renatobertacco are you happy with the state of that PR, and does it accomplish your needs? We're still working on the bundle support, both are currently scheduled for 0.6.1

**Comment by renatobertacco** [comment]
@cangencer yes, it works fine. Currently we are using the @viliam-durina branch for developing and by now we do not have found any problem. Thanks

**Comment by cangencer** [comment]
OK then I am closing this PR and we can continue discussion on the other one if you have any questions.

**Pull request closed without merging**
