### PR TITLE
Workaround AbstractInvocationFuture.thenApply issue

### LINKED ISSUE #2511: Job doesn't fail if exception is thrown from mapUsingIMap stage
In case when `mapUsingIMap` stage throws exception then job stops to process another items but it is not finished (it is still in a running state). This means users cannot detect that something went wrong. In correct behavior it should fail.

Use following pipeline to reproduce the issue:
```
Pipeline p = Pipeline.create();
p.readFrom(TestSources.itemStream(10))
        .withIngestionTimestamps()
        .mapUsingIMap("map", item -> "key", (item, value) -> {
            if (item.sequence() == 3) {
                throw new RuntimeException();
            }
            return item;
        }).setLocalParallelism(1)
        .writeTo(Sinks.logger());
```

### PR DESCRIPTION
**Pull request by viliam-durina**
Fixes #2511

### CODE REVIEW

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3269/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3269/jet-oss-pr-builder-3269.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-core: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java:662:38: '{' at column 38 should have line break after. [LeftCurly]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3271/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3271/jet-oss-pr-builder-3271.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:670 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[INFO] 
[ERROR] Tests run: 2219, Failures: 1, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3273/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3273/jet-oss-pr-builder-3273.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:670 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:670 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[INFO] 
[ERROR] Tests run: 2219, Failures: 2, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3274/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3274/jet-oss-pr-builder-3274.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:670 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[INFO] 
[ERROR] Tests run: 2219, Failures: 1, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Review by olukas — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3278/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3278/jet-oss-pr-builder-3278.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:671 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:671 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[INFO] 
[ERROR] Tests run: 2219, Failures: 2, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by viliam-durina** [comment]
Closing in favor of #2517

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3395/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3395/jet-oss-pr-builder-3395.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BatchStageTest.test_imdgIssue17515NotFixed:671 Issue https://github.com/hazelcast/hazelcast/issues/17515 was fixed, revert code in GeneralStage.mapUsingIMap()
[INFO] 
[ERROR] Tests run: 2219, Failures: 1, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Pull request closed without merging**
