### PR TITLE
Fix link in Jet JavaDoc

### PR DESCRIPTION
**Pull request by TisonKun**
Fix link in `Jet`'s JavaDoc, straightforward.

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by TisonKun** [comment]
Thanks for your review and merging!

**Comment by cangencer** [comment]
@TisonKun is it possible that you could sign  & email https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement ?

**Comment by TisonKun** [comment]
@cangencer yes of course. I've sent it.

BTW, I find hazelcast-jet is an interesting project. Are there some topics/developing events I can follow? Background: I'm one of Flink committers and developer of ray-streaming.

**Comment by cangencer** [comment]
@TisonKun you can join us on the gitter channel https://gitter.im/hazelcast/hazelcast-jet ? I don't know much about the Ray streaming project, would be curious to know more.

**Pull request merged**
