### PR TITLE
Stable api tweaks

### PR DESCRIPTION
**Pull request by viliam-durina**

### CODE REVIEW

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by cangencer** [comment]
Are there any breaking changes worth mentioning in release notes?

**Comment by viliam-durina** [comment]
Summary of breaking changes:
- renaming of methods in `ContextFactory`
- removed methods from `WindowDefinition`: these were most likely not used, probably not worth mentioning

**Pull request merged**
