### PR TITLE
Fix StreamSocketP failure

### LINKED ISSUE #2491: com.hazelcast.jet.impl.connector.StreamSocketPTest.smokeTest[input=1%n2%n, output=[1, 2]]
_master_ (commit a359b16cb2615f327219001138f3b318456a64c2)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/253/testReport/com.hazelcast.jet.impl.connector/StreamSocketPTest/smokeTest_input_1_n2_n__output__1__2__/

Stacktrace:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.jet.impl.connector.StreamSocketPTest.lambda$runTest$1(StreamSocketPTest.java:119)
	at com.hazelcast.jet.impl.connector.StreamSocketPTest$$Lambda$1523.000000001811EE70.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1373)
	at com.hazelcast.jet.impl.connector.StreamSocketPTest.runTest(StreamSocketPTest.java:119)
	at com.hazelcast.jet.impl.connector.StreamSocketPTest.smokeTest(StreamSocketPTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Standard output:
```
Hiccups measured while running test 'smokeTest[input=1%n2%n, output=[1, 2]](com.hazelcast.jet.impl.connector.StreamSocketPTest):'
01:57:35, accumulated pauses: 257 ms, max pause: 14 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by viliam-durina**
Also speed up the test (from 50 to 3 seconds)

Fixes #2491

### CODE REVIEW

**Review by gurbuzali — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3214/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3214/jet-oss-pr-builder-3214.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OperationLossTest.when_completeExecutionOperationLost_then_jobCompletes ? OperationTimeout
[INFO] 
[ERROR] Tests run: 2219, Failures: 0, Errors: 1, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3219/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3219/jet-oss-pr-builder-3219.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
There are changed files after building. This is forbidden, they should be add to PR or PR should be fixed. This mostly happens if there is any change in pom.xml which is not reflect in NOTICE file.
 M extensions/elasticsearch/elasticsearch-6/src/root/NOTICE
 M hazelcast-jet-distribution/src/root/NOTICE
</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Pull request merged**
