### PR TITLE
Unignore DeploymentTest

### PR DESCRIPTION
**Pull request by cangencer**

### CODE REVIEW

**Comment by viliam-durina** [comment]
Problem was in HZ's `FilteringClassLoader`, fix is in hazelcast/hazelcast#11584.

**Comment by mtopolnik** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
Since https://github.com/hazelcast/hazelcast/pull/11633 is merged, this should no longer fail.

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Pull request merged**
