### PR TITLE
ReadFileStreamP should not emit incomplete lines

### PR DESCRIPTION
**Pull request by viliam-durina**
Previously, lines from appended files could be emitted in two chunks, if we
read the file with concurrent writing. Also, only appended lines from
pre-existing files will be read.

### CODE REVIEW

**Comment by cangencer** [comment]
Does this fix the intermittently failing tests?

**Comment by viliam-durina** [comment]
No. I fact, I don't really understand, why they fail.

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
Don't merge, more stuff will come here.

**Comment by cangencer** [comment]
verify

**Pull request merged**
