### PR TITLE
[IGNORE] playing with PR builder

### PR DESCRIPTION
**Pull request by olukas**

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3216/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3216/jet-oss-pr-builder-3216.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
There are changed files after building. This is forbidden, they should be add to PR or PR should be fixed. This mostly happens if there is any change in pom.xml which is not reflect in NOTICE file.
 M extensions/elasticsearch/elasticsearch-6/src/root/NOTICE
 M hazelcast-jet-distribution/src/root/NOTICE
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3218/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3218/jet-oss-pr-builder-3218.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobRestartStressTest.stressTest_restart:31->JobRestartStressTestBase.stressTest:65->JetTestSupport.waitForFirstSnapshot:250->HazelcastTestSupport.assertTrueEventually:1373->HazelcastTestSupport.assertTrueEventually:1356->JetTestSupport.lambda$waitForFirstSnapshot$3:253 No snapshot produced
[ERROR]   HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts:90->HazelcastTestSupport.assertTrueEventually:1373->HazelcastTestSupport.assertTrueEventually:1356->lambda$when_iListWrittenAndMemberShutdown_then_jobRestarts$0:90 no output to sink
[INFO] 
[ERROR] Tests run: 2219, Failures: 2, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by olukas** [comment]
verify

**Comment by olukas** [comment]
verify

**Comment by olukas** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3233/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3233/jet-oss-pr-builder-3233.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SourceBuilderTest.test_faultTolerance:329->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance:329->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance_snapshotWithUserDefinedObject:354->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance_snapshotWithUserDefinedObject:354->testFaultTolerance:384 expected:<20> but was:<100>
[INFO] 
[ERROR] Tests run: 2219, Failures: 4, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3234/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3234/jet-oss-pr-builder-3234.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SourceBuilderTest.test_faultTolerance:329->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance:329->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance_snapshotWithUserDefinedObject:354->testFaultTolerance:384 expected:<20> but was:<100>
[ERROR]   SourceBuilderTest.test_faultTolerance_snapshotWithUserDefinedObject:354->testFaultTolerance:384 expected:<20> but was:<100>
[INFO] 
[ERROR] Tests run: 2219, Failures: 4, Errors: 0, Skipped: 10
[INFO] 

[ERROR] There are test failures.

There are changed files after building. This is forbidden, they should be add to PR or PR should be fixed. This mostly happens if there is any change in pom.xml which is not reflect in NOTICE file.
 M hazelcast-jet-distribution/src/root/NOTICE
</details>
</pre>

**Comment by olukas** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3240/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3240/jet-oss-pr-builder-3240.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
There are changed files after building. This is forbidden, they should be add to PR or PR should be fixed. This mostly happens if there is any change in pom.xml which is not reflect in NOTICE file.
 M hazelcast-jet-distribution/src/root/NOTICE
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3242/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3242/jet-oss-pr-builder-3242.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
There are changed files after building. This is forbidden, they should be add to PR or PR should be fixed. This mostly happens if there is any change in pom.xml which is not reflect in NOTICE file or if you are not using latest version of master branch.
 M hazelcast-jet-distribution/src/root/NOTICE
</details>
</pre>

**Comment by olukas** [comment]
verify

**Pull request closed without merging**
