### PR TITLE
Stuck phase 2 tests

### PR DESCRIPTION
**Pull request by viliam-durina**
Attempts to reproduce #2456

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3258/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3258/jet-oss-pr-builder-3258.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:check (default) on project hazelcast-jet-core: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3270/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3270/jet-oss-pr-builder-3270.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Pull request closed without merging**
