### PR TITLE
Fix local parallelism determination issue

### LINKED ISSUE #2739: Set localParallelism can be increased if preserveOrder=true
In case `preserveOrder` is set to `true` for pipeline and some stage has set local parallelism lower than default then it can be increased by pipeline to higher number than was set. We should count it as minimum of the upstream LP and set localParallelism.

### PR DESCRIPTION
**Pull request by ufukyilmaz**
This PR fixes the issue that -> the local parallelism determination logic incorrectly did not allow to set the local parallelism of a stage to the LP value that is lower than the LP of upstream stage.

Fixes #2739

Checklist:
- [x] Labels and Milestone set

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3798/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3798/jet-oss-pr-builder-3798.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java:[67,5] method does not override or implement a method from a supertype
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project hazelcast-jet-core: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java:[67,5] method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java:[67,5] method does not override or implement a method from a supertype
--------------------------
</details>
</pre>

**Comment by ufukyilmaz** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3822/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3822/jet-oss-pr-builder-3822.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaPTest.when_partitionAddedWhileJobDown_then_consumedFromBeginning:404->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->lambda$when_partitionAddedWhileJobDown_then_consumedFromBeginning$8:405 expected:<1> but was:<2>
[INFO] 
[ERROR] Tests run: 35, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by ufukyilmaz** [comment]
verify

**Review by olukas — APPROVED** [review]

**Pull request merged**
