### PR TITLE
Fix error handling in tryStartJob()

### PR DESCRIPTION
**Pull request by viliam-durina**
Every exception during tryStartJob should finalize the job with the error. The
previous alternative just ignored it and left the job in an inconsistent state.
What triggered this error was a non-serializable ProcessorSupplier that
implemented DataSerializable: it wasn't caught in `checkSerializable`, but
later when calling `toData(plan)`.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3019/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3019/jet-oss-pr-builder-3019.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobRepositoryTest.when_jobIsRunning_then_expiredJobIsNotCleanedUp:95
[ERROR]   JobRepositoryTest.when_jobRecordIsPresentForExpiredJob_then_jobIsNotCleanedUp:112
[INFO] 
[ERROR] Tests run: 2218, Failures: 2, Errors: 0, Skipped: 12
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by cangencer** [comment]
Just making a note that if this fix is for 4.2, it should be on 4.2 branch as well

**Comment by viliam-durina** [comment]
It's not critical. It happens only if the ProcessorSupplier is DataSerializable, there is also a ProcessorMetaSupplier. And it happens consistently during developemnt. But in this unlikely scenario, no error is logged and job gets stuck.

**Comment by viliam-durina** [comment]
verify

**Pull request merged**
