### PR TITLE
Improve default config file and docs on config options

### PR DESCRIPTION
**Pull request by mtopolnik**
Checklist
- [x] Tags Set
- [x] Milestone Set

### CODE REVIEW

**Review by jbartok — APPROVED** [review]

**Comment by mtopolnik** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-docs-no-build` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/277/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/277/jet-oss-pr-builder-docs-no-build-277.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
There are unexpected files.
Unexpected file: hazelcast-jet-distribution/src/root/config/hazelcast-jet.yaml
</details>
</pre>

**Comment by mtopolnik** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-docs-no-build` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/278/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/278/jet-oss-pr-builder-docs-no-build-278.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
There are unexpected files.
Unexpected file: hazelcast-jet-distribution/src/root/config/hazelcast-jet.yaml
</details>
</pre>

**Comment by mtopolnik** [comment]
verify

**Comment by olukas** [comment]
verify

**Pull request merged**
