### PR TITLE
Migrate CDC test container related fixes from `master`

### PR DESCRIPTION
**Pull request by jbartok**
Migrate CDC test container related fixes from `master`

Checklist:
- [x] Labels and Milestone set

### CODE REVIEW

**Comment by jbartok** [comment]
run-cdc-mysql-test

**Comment by jbartok** [comment]
run-cdc-postgres-test

**Comment by jbartok** [comment]
run-cdc-postgres-tests

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Review by olukas — APPROVED** [review]

**Comment by olukas** [comment]
verify

**Pull request merged**
